force-app/main/default/objects/Rest_Log__c/Rest_Log__c.object-meta.xml
<CustomObject>
    <description>Holds the log records for all REST API calls.</description>
    <label>REST Log</label>
    <nameField>
        <displayFormat>RL-{0000000000}</displayFormat>
        <label>Rest Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rest Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rest_Log__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>(End_Time__c - Start_Time__c)*24*60*60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rest_Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rest_Log_Event__e/Rest_Log_Event__e.object-meta.xml
<CustomObject>
    <label>Rest Log Event</label>
    <pluralLabel>Rest Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Rest_Log_Event__e/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <label>Error Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rest_Log_Event__e/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rest_Log_Event__e/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rest_Log_Event__e/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rest_Log_Event__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Rest_Log_Event_Test.cls
/**
 * Created by DDiaconescu on 28/12/2018.
 */

@IsTest
private class Rest_Log_Event_Test {
    @IsTest
    static void publishEvent() {
        String testString = TestUtils.generateRandomString(240);
        Datetime startTime = system.now();
        Datetime endTime = startTime.addSeconds(1);

        Rest_Log_Event__e restLogEvent = new Rest_Log_Event__e();
        restLogEvent.Method__c = 'GET';
        restLogEvent.Request_Body__c = testString + '_request_body';
        restLogEvent.Response_Body__c = testString + '_response_body';
        restLogEvent.Message__c = testString + '_message';
        restLogEvent.Status__c = 'Failure';
        restLogEvent.Endpoint__c = testString + '_endpoint';
        restLogEvent.Error_Code__c = '500';
        restLogEvent.Start_Time__c = startTime;
        restLogEvent.End_Time__c = endTime;

        Test.startTest();
        Database.SaveResult saveResult = EventBus.publish(restLogEvent);
        Test.stopTest();

        Rest_Log__c restLog = [SELECT Id, Method__c, Request_Body__c, Response_Body__c, Message__c, Status__c, Endpoint__c, Error_Code__c, Start_Time__c, End_Time__c, Duration__c FROM Rest_Log__c LIMIT 1];

        system.assert(restLog != null);
        system.assertEquals('GET', restLog.Method__c);
        system.assertEquals(testString + '_request_body', restLog.Request_Body__c);
        system.assertEquals(testString + '_response_body', restLog.Response_Body__c);
        system.assertEquals(testString + '_message', restLog.Message__c);
        system.assertEquals(testString + '_endpoint', restLog.Endpoint__c);
        system.assertEquals('Failure', restLog.Status__c);
        system.assertEquals('500', restLog.Error_Code__c);
        system.assertEquals(startTime, restLog.Start_Time__c);
        system.assertEquals(endTime, restLog.End_Time__c);
        system.assertEquals(1, restLog.Duration__c);

    }
}